# Generated by Django 4.1.1 on 2024-03-29 12:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='club_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='numericRoleLevel',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('resource_name', models.CharField(choices=[('audi', 'Auditorium'), ('sem', 'Seminar hall'), ('labs', 'labs'), ('classroom', 'classroom')], max_length=20, primary_key=True, serialize=False)),
                ('resource_type', models.IntegerField(default=0)),
                ('max_permission', models.IntegerField(default=3, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(3)])),
                ('current_permission', models.IntegerField(default=0)),
                ('userperms', models.JSONField(blank=True, default=list, null=True)),
                ('resource_head', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_resources', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now, null=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('all_true', models.BooleanField(default=False)),
                ('curr_index', models.IntegerField(default=0)),
                ('max_index', models.IntegerField(default=0)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='app1.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
