# Generated by Django 4.2.3 on 2024-03-30 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_user_club_name_user_is_admin_user_numericrolelevel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='numericRoleLevel',
        ),
    ]
