# Generated by Django 4.2.3 on 2024-03-31 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_user_numericrolelevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 31, 6, 50, 1, 764428, tzinfo=datetime.timezone.utc)),
        ),
    ]
