# Generated by Django 4.2.3 on 2024-03-31 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_user_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 31, 7, 31, 50, 940598, tzinfo=datetime.timezone.utc)),
        ),
    ]
