# Generated by Django 4.2.3 on 2024-03-31 08:56

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_user_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='numericRoleLevel',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 31, 8, 56, 37, 245430, tzinfo=datetime.timezone.utc)),
        ),
    ]
