# Generated by Django 4.2.3 on 2024-04-01 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_user_numericrolelevel_alter_user_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 1, 8, 53, 10, 737734, tzinfo=datetime.timezone.utc)),
        ),
    ]
