# Generated by Django 4.0.5 on 2024-04-02 08:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_user_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_name',
            field=models.CharField(choices=[('Auditorium', 'Auditorium'), ('sem', 'Seminar hall'), ('labs', 'labs'), ('classroom', 'classroom')], max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 2, 8, 42, 19, 375388, tzinfo=utc)),
        ),
    ]
