# Generated by Django 4.0.5 on 2024-04-06 18:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_resource_resource_name_alter_user_expires_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='club_name',
            new_name='organization',
        ),
        migrations.AlterField(
            model_name='user',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 6, 18, 55, 8, 414024, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
